name = "resume"
main = "src/index.ts"
compatibility_date = "2024-12-17"

# compatibility_flags = [ "nodejs_compat" ]

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "resume"
database_id = "29426d5d-33d7-48d4-8088-cd3c9046dc60"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
